"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";
import { RiLogoutCircleFill } from "react-icons/ri";
import { Providers } from "./providers";
import { useEffect, useRef, useState } from "react";
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
  useDisclosure,
  Button,
  Heading,
  ListItem,
  UnorderedList,
  Flex,
  Text,
  Box,
  Divider,
  Avatar,
} from "@chakra-ui/react";
import { useRouter } from "next/navigation";
import { CartWrapper } from "@/context/cart";
import { NavabarWrapper } from "@/context/navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   name: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const drawerRef = useRef(null);
  const router = useRouter();
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [isNavbarVisible, setIsNavbarVisible] = useState(true);

  const treatments = [
    { name: "Queda de cabelo" },
    { name: "Disfunção erétil" },
    { name: "Sono" },
    { name: "Perda de peso" },
  ];

  const suportLinks = [
    { name: "Central de ajuda" },
    { name: "FAQ" },
    { name: "Contatos" },
  ];

  return (
    <html suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <div>
          <Providers>
            <NavabarWrapper>
              <CartWrapper>
                <Navbar
                  onOpen={onOpen}
                  drawerRef={drawerRef}
                  isNavbarVisible={isNavbarVisible}
                />
                <Drawer
                  isOpen={isOpen}
                  placement="left"
                  onClose={onClose}
                  finalFocusRef={drawerRef}
                >
                  <DrawerOverlay />
                  <DrawerContent>
                    <DrawerCloseButton />
                    <DrawerBody mt="2rem">
                      <Box mb="4rem">
                        <Heading size="md">Tratamentos</Heading>
                        <Flex flexDir="column" mt="1rem">
                          <UnorderedList
                            color="brand.500"
                            style={{ marginLeft: "2rem" }}
                          >
                            {treatments.map((treatment, index) => (
                              <ListItem key={index} mt="1.5rem">
                                <Text color="#000">{treatment.name}</Text>
                              </ListItem>
                            ))}
                          </UnorderedList>
                        </Flex>
                      </Box>
                      <Divider />
                      <Box mt="4rem">
                        <Heading size="md">Suporte</Heading>
                        <Flex flexDir="column" mt="1rem">
                          <UnorderedList
                            color="brand.500"
                            style={{ marginLeft: "2rem" }}
                          >
                            {suportLinks.map((treatment, index) => (
                              <ListItem key={index} mt="1.5rem">
                                <Text color="#000">{treatment.name}</Text>
                              </ListItem>
                            ))}
                          </UnorderedList>
                        </Flex>
                      </Box>
                    </DrawerBody>

                    <DrawerFooter>
                      <Flex flexDir="column" rowGap="1rem">
                        <Flex
                          alignItems="center"
                          justifyContent="center"
                          gap="1rem"
                        >
                          <Text as="b">Sua conta, Usuário</Text>
                          <Avatar
                            margin={1}
                            mr="1rem"
                            color="black"
                            size="sm"
                            name="Dan Abrahmov"
                            src="https://bit.ly/dan-abramov"
                          />
                        </Flex>
                        <Box textAlign="right">
                          <Button
                            colorScheme="brand"
                            onClick={() => {
                              router.push("/login");
                              onClose();
                            }}
                            leftIcon={<RiLogoutCircleFill />}
                            rounded="full"
                            variant="ghost"
                          >
                            Sair
                          </Button>
                        </Box>
                      </Flex>
                    </DrawerFooter>
                  </DrawerContent>
                </Drawer>
                <div style={{ marginTop: "95px" }}>{children}</div>
              </CartWrapper>
            </NavabarWrapper>
          </Providers>
        </div>
      </body>
    </html>
  );
}
